### ISSUE TITLE
Eclipse maven error.

### ISSUE THREAD

**Issue by sggreener** [sggreener/GeoRaptor#12]
For some reason, I am now getting the following error in Eclipse when trying to compile GeoRaptor when previously I did not.

I've checked pom.xml but it hasn't changed.

[INFO] --- maven-bundle-plugin:3.5.1:bundle (default-bundle) @ GeoRaptor ---
[ERROR] An internal error occurred
java.io.IOException: invalid header field
	at java.util.jar.Attributes.read(Attributes.java:406)
	at java.util.jar.Manifest.read(Manifest.java:199)
	at java.util.jar.Manifest.<init>(Manifest.java:69)

Can you give me any pointers as to how to find this problem?

**Comment by sggreener** [comment]
MANIFEST.MD
